// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { mockSupabase } from "./mock-client";
import { toast } from "sonner";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  const isDefaultOrMock = 
    !SUPABASE_URL || 
    SUPABASE_URL.includes("your-project") || 
    SUPABASE_URL.includes("fbrcnxwypiccqazgyxbz") ||
    import.meta.env.VITE_USE_MOCK_SUPABASE === "true";

  if (isDefaultOrMock) {
    if (typeof window !== "undefined") {
      console.log("[Supabase] Unreachable or default Supabase project configured. Falling back to local Mock Client.");
      setTimeout(() => {
        try {
          toast.info("Offline Demo Mode Active", {
            description: "Using mock local database. Log in as farmer@agrifarm.com, officer@agrifarm.com, or admin@agrifarm.com (password: password123).",
            duration: 8000,
          });
        } catch (e) {
          // ignore if sonner is not ready
        }
      }, 1000);
    }
    return mockSupabase as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

